"""
Writes the recovered C++ project to disk.

Layout
------
output/recovered/<binary_name>/
    recovered.h          — forward declarations + type definitions
    recovered.cpp        — full function implementations
    function_index.txt   — address → name index for quick lookup
"""

import re
from pathlib import Path
from dataclasses import dataclass, field


@dataclass
class _FnRecord:
    name: str
    address: str
    cpp: str
    signature: str = ""   # Ghidra-provided signature (authoritative types/params)


class ProjectWriter:
    def __init__(self, output_dir: str, binary_name: str):
        self.out_root = Path(output_dir) / binary_name
        self.binary_name = binary_name
        self._functions: list[_FnRecord] = []

    def add_function(self, name: str, address: str, cpp: str, signature: str = ""):
        self._functions.append(_FnRecord(name=name, address=address, cpp=cpp.strip(), signature=signature))

    def write(self) -> Path:
        self.out_root.mkdir(parents=True, exist_ok=True)

        self._write_header()
        self._write_source()
        self._write_index()

        return self.out_root

    # ------------------------------------------------------------------
    # Header file
    # ------------------------------------------------------------------

    def _write_header(self):
        path = self.out_root / "recovered.h"
        lines = [
            f"// Recovered from: {self.binary_name}",
            f"// Functions: {len(self._functions)}",
            "// Generated by AI Semantic Decompiler",
            "",
            "#pragma once",
            "#include <cstdint>",
            "#include <cstddef>",
            "",
        ]

        # Collect struct/class/enum/typedef definitions from all functions
        type_defs = self._extract_type_definitions()
        if type_defs:
            lines.append("// ===== Recovered type definitions =====")
            lines.extend(type_defs)
            lines.append("")

        # Forward declarations
        lines.append("// ===== Function declarations =====")
        for fn in self._functions:
            sig = _declaration(fn)
            if sig:
                lines.append(f"// {fn.address}")
                lines.append(sig)
                lines.append("")

        path.write_text("\n".join(lines), encoding="utf-8")

    # ------------------------------------------------------------------
    # Source file
    # ------------------------------------------------------------------

    def _write_source(self):
        path = self.out_root / "recovered.cpp"
        lines = [
            f"// Recovered from: {self.binary_name}",
            f'#include "recovered.h"',
            "",
        ]

        for fn in self._functions:
            lines.append(f"// {'=' * 60}")
            lines.append(f"// {fn.name}  [{fn.address}]")
            lines.append(f"// {'=' * 60}")
            lines.append(fn.cpp)
            lines.append("")

        path.write_text("\n".join(lines), encoding="utf-8")

    # ------------------------------------------------------------------
    # Index
    # ------------------------------------------------------------------

    def _write_index(self):
        path = self.out_root / "function_index.txt"
        lines = [f"{'ADDRESS':<20} {'NAME'}", "-" * 60]
        for fn in sorted(self._functions, key=lambda f: f.address):
            lines.append(f"{fn.address:<20} {fn.name}")
        path.write_text("\n".join(lines), encoding="utf-8")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _extract_type_definitions(self) -> list[str]:
        """Pull struct/class/enum/typedef blocks out of all function bodies."""
        type_pattern = re.compile(
            r'^((?:struct|class|enum(?:\s+class)?|typedef\s+struct|typedef\s+enum)'
            r'\s+\w+[^;]*\{[^}]*\}\s*(?:\w+\s*)?;)',
            re.MULTILINE | re.DOTALL
        )
        seen: dict[str, str] = {}
        for fn in self._functions:
            for m in type_pattern.finditer(fn.cpp):
                defn = m.group(1).strip()
                # Key by the first identifier after the keyword
                name_m = re.search(r'(?:struct|class|enum\s+class|enum|typedef\s+\w+)\s+(\w+)', defn)
                key = name_m.group(1) if name_m else defn[:30]
                if key not in seen:
                    seen[key] = defn

        result = []
        for defn in seen.values():
            result.append(defn)
            result.append("")
        return result


# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------

def _declaration(fn: "_FnRecord") -> str:
    """
    Build the forward declaration for a function.

    Primary path: use the Ghidra-provided signature (authoritative types and
    parameter count) but substitute the Ghidra placeholder name (FUN_xxx) with
    the semantic name the AI chose in the reconstructed code.

    Fallback: if Ghidra gave no signature, extract the declaration from the
    AI-generated cpp the old heuristic way.
    """
    if fn.signature:
        # Pull the function name out of the Ghidra signature, e.g.
        # "undefined8 FUN_140001330(undefined8 * param_1)"  →  "FUN_140001330"
        m = re.search(r'\b([A-Za-z_]\w*)\s*\(', fn.signature)
        if m:
            ghidra_name = m.group(1)
            decl = fn.signature.replace(ghidra_name, fn.name, 1)
        else:
            decl = fn.signature
        return decl.rstrip(";") + ";"

    return _extract_signature_fallback(fn.cpp)


def _extract_signature_fallback(cpp: str) -> str:
    """Heuristic fallback: fish the function signature out of AI-generated code."""
    SKIP = re.compile(r'^(struct|class|enum|typedef|extern)\b')
    in_block_comment = False
    lines = cpp.split("\n")

    for i, line in enumerate(lines):
        s = line.strip()
        if in_block_comment:
            if "*/" in s:
                in_block_comment = False
            continue
        if s.startswith("/*"):
            if "*/" not in s:
                in_block_comment = True
            continue
        if not s or s.startswith("//") or s.startswith("#"):
            continue
        if SKIP.match(s):
            continue
        if "(" not in s:
            continue
        if s.endswith(";") and "{" not in s:
            continue   # forward declaration, not a definition

        if "{" in s:
            return s.split("{")[0].rstrip() + ";"

        # Multi-line signature — confirm next non-blank line opens the body
        for j in range(i + 1, min(i + 5, len(lines))):
            next_s = lines[j].strip()
            if next_s.startswith("{"):
                return s + ";"
            if next_s and not next_s.startswith("//"):
                break

    return ""
