"""
Writes the recovered C++ project to disk.

Layout
------
output/recovered/<binary_name>/
    recovered.h          — forward declarations + type definitions
    recovered.cpp        — full function implementations
    function_index.txt   — address → name index for quick lookup
"""

import re
from pathlib import Path
from dataclasses import dataclass, field


@dataclass
class _FnRecord:
    name: str
    address: str
    cpp: str
    signature: str = ""   # Ghidra-provided signature (authoritative types/params)


class ProjectWriter:
    def __init__(self, output_dir: str, binary_name: str):
        self.out_root = Path(output_dir) / binary_name
        self.binary_name = binary_name
        self._functions: list[_FnRecord] = []

    def add_function(self, name: str, address: str, cpp: str, signature: str = ""):
        self._functions.append(_FnRecord(name=name, address=address, cpp=cpp.strip(), signature=signature))

    def write(self) -> Path:
        self.out_root.mkdir(parents=True, exist_ok=True)

        self._write_header()
        self._write_source()
        self._write_index()

        return self.out_root

    # ------------------------------------------------------------------
    # Header file
    # ------------------------------------------------------------------

    def _write_header(self):
        path = self.out_root / "recovered.h"
        lines = [
            f"// Recovered from: {self.binary_name}",
            f"// Functions: {len(self._functions)}",
            "// Generated by AI Semantic Decompiler",
            "",
            "#pragma once",
            "#include <cstdint>",
            "#include <cstddef>",
            "",
        ]

        # Collect struct/class/enum/typedef definitions from all functions
        type_defs = self._extract_type_definitions()
        if type_defs:
            lines.append("// ===== Recovered type definitions =====")
            lines.extend(type_defs)
            lines.append("")

        # Forward declarations
        lines.append("// ===== Function declarations =====")
        for fn in self._functions:
            sig = _declaration(fn)
            if sig:
                lines.append(f"// {fn.address}")
                lines.append(sig)
                lines.append("")

        path.write_text("\n".join(lines), encoding="utf-8")

    # ------------------------------------------------------------------
    # Source file
    # ------------------------------------------------------------------

    def _write_source(self):
        path = self.out_root / "recovered.cpp"
        lines = [
            f"// Recovered from: {self.binary_name}",
            f'#include "recovered.h"',
            "",
        ]

        for fn in self._functions:
            lines.append(f"// {'=' * 60}")
            lines.append(f"// {fn.name}  [{fn.address}]")
            lines.append(f"// {'=' * 60}")
            lines.append(fn.cpp)
            lines.append("")

        path.write_text("\n".join(lines), encoding="utf-8")

    # ------------------------------------------------------------------
    # Index
    # ------------------------------------------------------------------

    def _write_index(self):
        path = self.out_root / "function_index.txt"
        lines = [f"{'ADDRESS':<20} {'NAME'}", "-" * 60]
        for fn in sorted(self._functions, key=lambda f: f.address):
            lines.append(f"{fn.address:<20} {fn.name}")
        path.write_text("\n".join(lines), encoding="utf-8")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _extract_type_definitions(self) -> list[str]:
        """Pull struct/class/enum/typedef blocks out of all function bodies."""
        seen: dict[str, str] = {}
        for fn in self._functions:
            for defn, key in _find_type_definitions(fn.cpp):
                if key not in seen:
                    seen[key] = defn

        result = []
        for defn in seen.values():
            result.append(defn)
            result.append("")
        return result


# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------

_TYPE_START_RE = re.compile(
    r'^(?:struct|class|enum(?:\s+class)?|typedef\s+struct|typedef\s+enum)'
    r'\s+(?P<name>\w+)\b[^{;]*\{',
    re.MULTILINE
)


def _matching_brace(code: str, open_pos: int):
    """Index of the `}` that closes the `{` at `open_pos`, or None if unbalanced."""
    depth = 0
    for i in range(open_pos, len(code)):
        if code[i] == "{":
            depth += 1
        elif code[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    return None


def _find_type_definitions(code: str):
    """
    Yield (definition_text, name) for each top-level struct/class/enum/
    typedef block in `code`, using real brace-depth matching instead of a
    single-level regex. A naive `\\{[^}]*\\}` can't handle a class with an
    inline method body (its own nested braces) — it truncates at the first
    inner `}` it finds (e.g. a constructor's closing brace) rather than the
    type's own closing brace, silently emitting a broken fragment that reads
    as complete syntax (`class X { ... };`) but isn't actually the whole
    class. This showed up for real: a `CRTStartup` class with an inline
    constructor got truncated this way, leaving its real closing brace
    missing and several unrelated classes accidentally nested inside it in
    the generated header.
    """
    for m in _TYPE_START_RE.finditer(code):
        open_brace = m.end() - 1
        close_brace = _matching_brace(code, open_brace)
        if close_brace is None:
            continue  # unbalanced in the source — skip rather than emit a truncated fragment
        tail = re.match(r'\s*(\w*)\s*;', code[close_brace + 1: close_brace + 41])
        if not tail:
            continue  # not actually followed by a declarator/`;` — not a complete definition
        end = close_brace + 1 + tail.end()
        yield code[m.start():end].strip(), m.group("name")


def _declaration(fn: "_FnRecord") -> str:
    """
    Build the forward declaration for a function.

    Primary path: use the Ghidra-provided signature (authoritative types and
    parameter count) but substitute the Ghidra placeholder name (FUN_xxx) with
    the semantic name the AI chose in the reconstructed code.

    Fallback: if Ghidra gave no signature, extract the declaration from the
    AI-generated cpp the old heuristic way.
    """
    if fn.signature:
        # Pull the function name out of the Ghidra signature, e.g.
        # "undefined8 FUN_140001330(undefined8 * param_1)"  →  "FUN_140001330"
        m = re.search(r'\b([A-Za-z_]\w*)\s*\(', fn.signature)
        if m:
            ghidra_name = m.group(1)
            decl = fn.signature.replace(ghidra_name, fn.name, 1)
        else:
            decl = fn.signature
        return decl.rstrip(";") + ";"

    return _extract_signature_fallback(fn.cpp)


def _extract_signature_fallback(cpp: str) -> str:
    """Heuristic fallback: fish the function signature out of AI-generated code."""
    SKIP = re.compile(r'^(struct|class|enum|typedef|extern)\b')
    in_block_comment = False
    lines = cpp.split("\n")

    for i, line in enumerate(lines):
        s = line.strip()
        if in_block_comment:
            if "*/" in s:
                in_block_comment = False
            continue
        if s.startswith("/*"):
            if "*/" not in s:
                in_block_comment = True
            continue
        if not s or s.startswith("//") or s.startswith("#"):
            continue
        if SKIP.match(s):
            continue
        if "(" not in s:
            continue
        if s.endswith(";") and "{" not in s:
            continue   # forward declaration, not a definition

        if "{" in s:
            return s.split("{")[0].rstrip() + ";"

        # Multi-line signature — confirm next non-blank line opens the body
        for j in range(i + 1, min(i + 5, len(lines))):
            next_s = lines[j].strip()
            if next_s.startswith("{"):
                return s + ";"
            if next_s and not next_s.startswith("//"):
                break

    return ""
