"""
Writes the recovered C++ project to disk.

Layout
------
output/recovered/<binary_name>/
    recovered.h          — forward declarations + type definitions
    recovered.cpp        — full function implementations
    function_index.txt   — address → name index for quick lookup
"""

import re
from pathlib import Path
from dataclasses import dataclass, field

from analyzer.library_signatures import _this_param_type


@dataclass
class _FnRecord:
    name: str
    address: str
    cpp: str
    signature: str = ""   # Ghidra-provided signature (authoritative types/params)


@dataclass
class _ExcludedRecord:
    name: str
    address: str
    reason: str
    signature: str = ""   # Ghidra-provided signature, when available (for forward-declaring it)


class ProjectWriter:
    def __init__(self, output_dir: str, binary_name: str):
        self.out_root = Path(output_dir) / binary_name
        self.binary_name = binary_name
        self._functions: list[_FnRecord] = []
        self._excluded: list[_ExcludedRecord] = []

    def add_function(self, name: str, address: str, cpp: str, signature: str = ""):
        self._functions.append(_FnRecord(name=name, address=address, cpp=cpp.strip(), signature=signature))

    def add_excluded(self, name: str, address: str, reason: str, signature: str = ""):
        """
        A function deliberately skipped by analyzer/library_signatures.py's
        translation_exclusion_reason() (STL/libstdc++ internal, an
        unresolved-self-call artifact, or MinGW CRT/runtime plumbing) —
        kept out of recovered.cpp/h entirely, but still listed in
        function_index.txt so nothing silently disappears from view.
        `signature` (Ghidra's own, when available) lets _write_header()
        forward-declare it for real if kept application code actually
        calls it (e.g. main() calling __main()) -- without that, such a
        call site would have nothing to compile against at all.
        """
        self._excluded.append(_ExcludedRecord(name=name, address=address, reason=reason, signature=signature))

    def write(self) -> Path:
        self.out_root.mkdir(parents=True, exist_ok=True)

        # Deterministic, no AI involved: aggregate every member function's
        # own real Ghidra `this`-typed signature into a proper class
        # declaration, and make sure each member's own out-of-line
        # definition is actually qualified as ClassName::member. Must run
        # before either file is written -- _write_header() needs the
        # synthesized classes, and _write_source() needs the qualified text.
        self._class_members, self._class_bases, self._class_fields = self._synthesize_class_members()
        self._qualify_member_definitions()

        self._write_header()
        self._write_source()
        self._write_index()

        return self.out_root

    # ------------------------------------------------------------------
    # Header file
    # ------------------------------------------------------------------

    def _write_header(self):
        path = self.out_root / "recovered.h"
        lines = [
            f"// Recovered from: {self.binary_name}",
            f"// Functions: {len(self._functions)}",
            "// Generated by AI Semantic Decompiler",
            "",
            "#pragma once",
            "#include <cstdint>",
            "#include <cstddef>",
            "#include <cstdio>",
            "#include <cstring>",
            "#include <string>",
            "#include <vector>",
            "#include <memory>",
            "#include <iostream>",
            "#ifdef _WIN32",
            "#include <windows.h>",
            "#endif",
            "",
            # AI-reconstructed method bodies routinely use bare `string`/
            # `allocator`/etc. (unqualified, no "std::") -- each function
            # was originally translated in isolation with no header of its
            # own to see, so there was never a `using` for it to rely on
            # consistently. Without this, a bare `string*` here is an
            # "unknown type" compile error, on top of and independent of
            # whatever else is wrong with the surrounding statement. This is
            # a recovered project meant to be read/built as one unit, not a
            # library header meant for other projects to include, so a
            # global `using namespace std;` is an acceptable, deliberate
            # tradeoff here.
            "using namespace std;",
            "",
        ]

        # AI-extracted struct/class/enum/typedef blocks -- but never for a
        # class name this run also synthesized member declarations for
        # (see _synthesize_class_members): those are deterministic and
        # complete (every member Ghidra evidences, aggregated across every
        # function that touches the class), where a per-function AI
        # fragment is neither -- each function only ever sees and
        # describes its own one method, never the class as a whole, so
        # two functions independently "reconstructing" the same class can
        # easily disagree.
        type_defs = self._extract_type_definitions(skip=set(self._class_members))
        if type_defs:
            lines.append("// ===== Recovered type definitions =====")
            lines.extend(type_defs)
            lines.append("")

        if self._class_members:
            lines.append("// ===== Synthesized class declarations =====")
            lines.append("// Member lists are aggregated deterministically from every")
            lines.append("// function's own real Ghidra `this`-typed signature, not from")
            lines.append("// any single function's own (partial, sometimes inconsistent)")
            lines.append("// idea of the class -- see _synthesize_class_members().")
            lines.append("")
            # Forward-declare every synthesized class *before* any full
            # definition -- inheritance needs bases fully defined first
            # (handled by the ordering below), but a method elsewhere can
            # just as easily take another synthesized class as a pointer
            # parameter, and a pointer parameter only ever needs a forward
            # declaration, never a full definition, regardless of
            # definition order. Declaring all of them upfront removes that
            # ordering dependency entirely instead of trying to
            # topologically sort every possible cross-reference.
            for class_name in self._class_members:
                lines.append(f"class {class_name};")
            lines.append("")
            for class_name in self._ordered_class_names():
                base = self._class_bases.get(class_name)
                header = f"class {class_name}" + (f" : public {base}" if base else "")
                lines.append(header + " {")
                lines.append("public:")
                for decl in self._class_members[class_name]:
                    lines.append(f"    {decl}")
                for field_name in self._class_fields.get(class_name, []):
                    # Generic fallback type: every observed case so far is
                    # a simple flag/offset, and `int` is both idiomatic for
                    # that and small enough that a real mismatch would
                    # surface immediately -- unlike a missing field
                    # entirely, which nothing downstream could recover.
                    lines.append(f"    int {field_name};  // type inferred generically -- see _detect_fields()")
                lines.append("};")
                lines.append("")

        # Forward declarations -- skips member functions entirely; those
        # are declared inside their class above instead, not as free
        # functions with an explicit `this` parameter.
        lines.append("// ===== Function declarations =====")
        for fn in self._functions:
            if _this_param_type(fn.signature):
                continue
            sig = _declaration(fn)
            if sig:
                lines.append(f"// {fn.address}")
                lines.append(_normalize_operator_dot_syntax(sig))
                lines.append("")

        excluded_decls = self._referenced_excluded_declarations()
        if excluded_decls:
            lines.append("// ===== Excluded runtime/library symbols this project's own code calls =====")
            lines.append("// Real CRT/library functions -- not implemented here (the real linked")
            lines.append("// CRT/library provides them), declared only so the calling code compiles.")
            lines.extend(excluded_decls)
            lines.append("")

        path.write_text("\n".join(lines), encoding="utf-8")

    def _referenced_excluded_declarations(self) -> list:
        """
        A forward declaration for every excluded symbol that some kept
        function's own code actually calls by name -- without this, a
        call like `__main();` inside a kept `main()` has nothing to
        compile against at all. Uses Ghidra's own signature when
        available; falls back to a permissive variadic-void declaration
        for the rare case there isn't one, rather than guessing a shape.
        """
        all_cpp = "\n".join(fn.cpp for fn in self._functions)
        decls, seen = [], set()
        for rec in self._excluded:
            if rec.reason.startswith("STL/libstdc++"):
                # Real class/template internals (string constructors,
                # _M_* members, ...) can't be forward-declared as plain
                # free functions at all -- they're not functions, they're
                # members of a real type <string>/etc. already provides.
                # If kept code is calling one by bare name, that's a real
                # bug in that code, not something a declaration here
                # could ever paper over.
                continue
            bare_name = _sanitize_identifier(rec.name)
            if not bare_name or bare_name in seen:
                continue
            if not re.search(rf'\b{re.escape(bare_name)}\s*\(', all_cpp):
                continue
            seen.add(bare_name)
            if rec.signature:
                sig = rec.signature
                if _is_operator_name(bare_name):
                    sig = _pointers_to_references(sig)
                # `this` is only a keyword when it's actually inside a
                # member function -- here it's just Ghidra's parameter
                # *name* for what's being forward-declared as a plain free
                # function, and "this" is reserved even as a parameter
                # name outside that context.
                sig = re.sub(r'\bthis\b', 'self_ptr', sig)
                decls.append(_normalize_operator_dot_syntax(_sanitize_ghidra_types(sig.rstrip(";") + ";")))
            else:
                decls.append(f'extern "C" void {bare_name}(...);')
        return decls

    def _ordered_class_names(self) -> list:
        """
        Bases before derived classes, so `class King : public Piece` never
        appears before `Piece` itself is defined. Classes whose base never
        gets resolved (rare -- e.g. a genuine cycle) are emitted last
        regardless, rather than dropped.
        """
        remaining = list(self._class_members)
        ordered = []
        emitted = set()
        while remaining:
            progressed = False
            for name in list(remaining):
                base = self._class_bases.get(name)
                if base is None or base in emitted or base not in self._class_members:
                    ordered.append(name)
                    emitted.add(name)
                    remaining.remove(name)
                    progressed = True
            if not progressed:
                ordered.extend(remaining)
                break
        return ordered

    # ------------------------------------------------------------------
    # Source file
    # ------------------------------------------------------------------

    def _write_source(self):
        path = self.out_root / "recovered.cpp"
        lines = [
            f"// Recovered from: {self.binary_name}",
            f'#include "recovered.h"',
            "",
        ]

        for fn in self._functions:
            lines.append(f"// {'=' * 60}")
            lines.append(f"// {fn.name}  [{fn.address}]")
            lines.append(f"// {'=' * 60}")
            lines.append(_normalize_operator_dot_syntax(_strip_type_definitions(fn.cpp)))
            lines.append("")

        path.write_text("\n".join(lines), encoding="utf-8")

    # ------------------------------------------------------------------
    # Index
    # ------------------------------------------------------------------

    def _write_index(self):
        path = self.out_root / "function_index.txt"
        lines = [f"{'ADDRESS':<20} {'NAME'}", "-" * 60]
        for fn in sorted(self._functions, key=lambda f: f.address):
            lines.append(f"{fn.address:<20} {fn.name}")

        if self._excluded:
            lines.append("")
            lines.append("EXCLUDED (library/runtime code, not application logic -- not in recovered.cpp/h)")
            lines.append("-" * 60)
            for fn in sorted(self._excluded, key=lambda f: f.address):
                lines.append(f"{fn.address:<20} {fn.name:<30} {fn.reason}")

        path.write_text("\n".join(lines), encoding="utf-8")

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _extract_type_definitions(self, skip: set = frozenset()) -> list[str]:
        """Pull struct/class/enum/typedef blocks out of all function bodies,
        except any name in `skip` (classes synthesized deterministically
        instead -- see write())."""
        seen: dict[str, str] = {}
        for fn in self._functions:
            for start, end, key in _find_type_definitions(fn.cpp):
                if key not in seen and key not in skip:
                    seen[key] = fn.cpp[start:end].strip()

        result = []
        for defn in seen.values():
            result.append(defn)
            result.append("")
        return result

    def _synthesize_class_members(self):
        """
        {class_name: [member_decl, ...]}, {class_name: base_class_name},
        {class_name: [field_name, ...]} -- methods are aggregated
        deterministically from every function's own real Ghidra
        `this`-typed signature, not from anything the AI wrote: Ghidra
        already tells us, per function, which class it's a member of,
        what it returns, and what its parameters are (minus `this`, which
        real C++ never redeclares). Fields are the one thing Ghidra's
        per-function signature genuinely cannot tell us -- there's no
        separate "field" export to consult here, only whatever the AI's
        own body code writes via `this->fieldName` -- so those are
        collected from every member function's body instead (see
        _detect_fields()) and unioned per class.
        """
        classes: dict = {}
        bases: dict = {}
        fields: dict = {}

        # Every class name that appears as *some* function's own `this`-
        # typed signature -- used below to tell a real base-class
        # constructor call apart from a same-shaped member-variable
        # initializer. Both look syntactically identical in an initializer
        # list (`identifier(args)`), so a real, observed bug matched
        # `Piece() : m_ptr(nullptr), m_active(false) {}`'s own member
        # initializer "m_ptr(nullptr)" as if "m_ptr" were Piece's base
        # class. Restricting accepted matches to names this run has
        # actually seen as *some* function's `this` type rules that out --
        # "m_ptr" is never any function's `this` type, but "Piece" is.
        known_class_names = {
            _this_param_type(fn.signature) for fn in self._functions
            if _this_param_type(fn.signature)
        }

        for fn in self._functions:
            this_type = _this_param_type(fn.signature)
            if not this_type:
                continue

            for field_name in _detect_fields(fn.cpp):
                if field_name not in fields.setdefault(this_type, []):
                    fields[this_type].append(field_name)

            orig_name = _original_ghidra_name(fn.signature)
            params = _param_list_without_this(fn.signature)

            if orig_name == this_type:
                decl = f"{this_type}({params});"
                base = _detect_base_class(fn.cpp, this_type, known_class_names)
                if base:
                    bases[this_type] = base
                for field_name in _detect_init_list_fields(fn.cpp, this_type, known_class_names):
                    if field_name not in fields.setdefault(this_type, []):
                        fields[this_type].append(field_name)
            elif orig_name == "~" + this_type:
                decl = f"~{this_type}();"
            else:
                member_name = _sanitize_identifier(fn.name) or orig_name
                # Prefer the AI's own parameter list too, for the same
                # reason as the return type just below -- Ghidra's own
                # types here are frequently erased/generic where the AI's
                # real definition has a specific, correct one. Some AI
                # definitions keep an explicit `this` parameter (C-style,
                # rather than relying on it being implicit); that's never
                # valid in a member *declaration* either way, so it's
                # dropped regardless of which source the params came from.
                params = _drop_this_param(_actual_params(fn.cpp, this_type, member_name)) or params
                # Prefer whatever return type the AI's own out-of-line
                # definition actually uses -- type annotation is one of
                # the things the annotation-task prompt explicitly asks it
                # to add, so it's usually a real type where Ghidra's own
                # signature only has a placeholder ("undefined"/
                # "undefined8", neither of which is valid C++). Only fall
                # back to Ghidra's signature, mapped through
                # _GHIDRA_PLACEHOLDER_TYPES, if the AI's own text doesn't
                # clarify it either.
                ret = (_actual_return_type(fn.cpp, this_type, member_name)
                       or _GHIDRA_PLACEHOLDER_TYPES.get(_return_type(fn.signature), _return_type(fn.signature)))
                # Ghidra's own signature has no notion of a const member
                # function at all (it's a low-level ABI view) -- this can
                # only come from the AI's own definition, and a
                # synthesized declaration that doesn't carry it through is
                # a declaration/definition mismatch: a real, observed
                # compile error (`Piece::Draw() const` defined, `Draw()`
                # declared, with nothing here to catch the difference).
                const_kw = " const" if _actual_is_const(fn.cpp, this_type, member_name) else ""
                decl = f"{ret} {member_name}({params}){const_kw};"

            decl = _sanitize_ghidra_types(decl)

            # Dedup identical declarations -- Ghidra occasionally reports
            # two distinct addresses with the exact same erased signature,
            # which would otherwise redeclare the same member twice and
            # fail to compile on its own.
            if decl not in classes.setdefault(this_type, []):
                classes[this_type].append(decl)

        return classes, bases, fields

    def _qualify_member_definitions(self):
        """
        Ensure every member function's own out-of-line definition is
        actually qualified as ClassName::member. Some AI output already
        does this correctly; some drops the qualifier entirely and
        defines what then becomes an unrelated free function that never
        attaches to the class at all. Mutates self._functions[...].cpp in
        place; called once from write() before either output file is
        generated.
        """
        for fn in self._functions:
            this_type = _this_param_type(fn.signature)
            if not this_type:
                continue
            orig_name = _original_ghidra_name(fn.signature)
            member_name = _sanitize_identifier(fn.name) or orig_name
            fn.cpp = _qualify_member_definition(fn.cpp, this_type, orig_name, member_name)


# ---------------------------------------------------------------------------
# Module-level helpers
# ---------------------------------------------------------------------------

_TYPE_START_RE = re.compile(
    r'^(?:struct|class|enum(?:\s+class)?|typedef\s+struct|typedef\s+enum)'
    r'\s+(?P<name>\w+)\b[^{;]*\{',
    re.MULTILINE
)


def _matching_brace(code: str, open_pos: int):
    """Index of the `}` that closes the `{` at `open_pos`, or None if unbalanced."""
    depth = 0
    for i in range(open_pos, len(code)):
        if code[i] == "{":
            depth += 1
        elif code[i] == "}":
            depth -= 1
            if depth == 0:
                return i
    return None


def _matching_paren(code: str, open_pos: int):
    """Index of the `)` that closes the `(` at `open_pos`, or None if unbalanced."""
    depth = 0
    for i in range(open_pos, len(code)):
        if code[i] == "(":
            depth += 1
        elif code[i] == ")":
            depth -= 1
            if depth == 0:
                return i
    return None


def _find_type_definitions(code: str):
    """
    Yield (start, end, name) for each top-level struct/class/enum/typedef
    block in `code`, using real brace-depth matching instead of a
    single-level regex. A naive `\\{[^}]*\\}` can't handle a class with an
    inline method body (its own nested braces) — it truncates at the first
    inner `}` it finds (e.g. a constructor's closing brace) rather than the
    type's own closing brace, silently emitting a broken fragment that reads
    as complete syntax (`class X { ... };`) but isn't actually the whole
    class. This showed up for real: a `CRTStartup` class with an inline
    constructor got truncated this way, leaving its real closing brace
    missing and several unrelated classes accidentally nested inside it in
    the generated header. `start`/`end` (not the sliced text) are returned
    so callers can also use this to strip a match back out of the original
    text (see _strip_type_definitions).
    """
    for m in _TYPE_START_RE.finditer(code):
        open_brace = m.end() - 1
        close_brace = _matching_brace(code, open_brace)
        if close_brace is None:
            continue  # unbalanced in the source — skip rather than emit a truncated fragment
        tail = re.match(r'\s*(\w*)\s*;', code[close_brace + 1: close_brace + 41])
        if not tail:
            continue  # not actually followed by a declarator/`;` — not a complete definition
        yield m.start(), close_brace + 1 + tail.end(), m.group("name")


def _strip_type_definitions(code: str) -> str:
    """
    Remove every top-level struct/class/enum/typedef block from `code` —
    used when writing a function into recovered.cpp, since recovered.h
    (included at the top of that file) already carries every recovered
    type definition exactly once, via ProjectWriter._extract_type_definitions().
    Leaving a type definition inline in a function's own text too meant the
    same type could get redefined verbatim by every function whose own
    output happened to include it — a real, observed failure: `class
    Exception`/`class String`/etc. each redeclared 2-3 times across
    different functions' own output, a hard redefinition error the moment
    more than one landed in the same translation unit.
    """
    spans = [(start, end) for start, end, _ in _find_type_definitions(code)]
    for start, end in reversed(spans):
        code = code[:start] + code[end:]
    return code.strip()


_OPERATOR_DOT_RE = re.compile(r'operator\.(new|delete)(\[\])?')


def _normalize_operator_dot_syntax(text: str) -> str:
    """
    Ghidra spells operator new/delete overloads with a literal dot --
    "operator.new", "operator.new[]" -- which the model preserves exactly
    (correctly, per its own instructions to copy anything it didn't itself
    declare/rename verbatim), but that's not valid C++ syntax; real C++
    needs a space ("operator new"). A fixed, unambiguous text substitution,
    not a judgment call, so it's done here rather than left to the model
    to remember correctly on every occurrence.
    """
    return _OPERATOR_DOT_RE.sub(lambda m: f"operator {m.group(1)}{m.group(2) or ''}", text)


_BRACKET_TAG_RE = re.compile(r'\[.*?\]')  # Ghidra ABI-version tags, e.g. the
# "[abi:cxx11]" GCC appends to symbols whose signature changed across the
# C++11 std::string ABI break -- not valid in a real identifier.


def _sanitize_identifier(name: str) -> str:
    return _BRACKET_TAG_RE.sub('', name)


_TRAILING_NAME_RE = re.compile(r'[\w.<>\[\]~:]+$')


def _original_ghidra_name(signature: str) -> str:
    """The bare method name exactly as Ghidra spelled it in `signature`
    (never AI-substituted) -- used to tell a constructor (`name ==
    this_type`) or destructor (`name == "~" + this_type`) apart from a
    regular method, since Ghidra's own naming convention for those is the
    class name itself, with no separate marker."""
    paren_idx = signature.find("(")
    if paren_idx == -1:
        return ""
    m = _TRAILING_NAME_RE.search(signature[:paren_idx].rstrip())
    return m.group(0) if m else ""


def _drop_this_param(param_list: str) -> str:
    """Remove any parameter literally named `this` -- real C++ member
    *declarations* never redeclare it, whether it came from Ghidra's own
    signature (which always spells it out explicitly) or from an AI
    definition that kept an explicit C-style `this` parameter instead of
    relying on it being implicit."""
    if not param_list.strip():
        return param_list
    kept = [p.strip() for p in param_list.split(",") if not re.search(r'\bthis\b', p)]
    return ", ".join(kept)


def _param_list_without_this(signature: str) -> str:
    """Parameter list from a Ghidra signature with the `this` parameter
    dropped -- real C++ member declarations never redeclare `this`."""
    open_idx = signature.find("(")
    close_idx = signature.rfind(")")
    if open_idx == -1 or close_idx == -1 or close_idx < open_idx:
        return ""
    return _drop_this_param(signature[open_idx + 1:close_idx])


def _return_type(signature: str) -> str:
    """Return type from a Ghidra signature, e.g. 'King * Draw(...)' -> 'King *'."""
    paren_idx = signature.find("(")
    prefix = signature[:paren_idx].rstrip() if paren_idx != -1 else signature
    m = _TRAILING_NAME_RE.search(prefix)
    return prefix[:m.start()].rstrip() if m else prefix


# Ghidra's own placeholder types for a return value it couldn't resolve --
# never valid C++ on their own. "undefined" (bare) most often really does
# mean "nothing meaningful is returned", so void is the reasonable default;
# the sized variants map to same-width unsigned integers, a neutral choice
# that at least compiles for whatever's actually returned.
_GHIDRA_PLACEHOLDER_TYPES = {
    "undefined": "void",
    "undefined1": "uint8_t",
    "undefined2": "uint16_t",
    "undefined4": "uint32_t",
    "undefined8": "uint64_t",
}


def _actual_return_type(cpp: str, class_name: str, member_name: str) -> str:
    """
    Best-effort: the return type actually written in `cpp`'s own out-of-
    line definition (e.g. 'int Rook::Move(...)' -> 'int'), preferred over
    Ghidra's own placeholder signature -- type annotation is one of the
    few things the annotation-task prompt explicitly asks the model to
    add, so its own choice here is usually real, where Ghidra's own
    signature for the same function is often just "undefined"/"undefined8".
    Returns "" (not a guess) if neither the qualified nor bare form of the
    definition can be found at all.
    """
    for pattern in (rf'{re.escape(class_name)}::{re.escape(member_name)}\s*\(',
                    rf'(?<![\w:]){re.escape(member_name)}\s*\('):
        m = re.search(pattern, cpp)
        if m:
            line_start = cpp.rfind('\n', 0, m.start()) + 1
            prefix = cpp[line_start:m.start()].strip()
            if prefix:
                return prefix
    return ""


def _actual_params(cpp: str, class_name: str, member_name: str) -> str:
    """
    Best-effort: the parameter list actually written in `cpp`'s own out-of-
    line definition, preferred over Ghidra's raw signature for the same
    reason as _actual_return_type -- the AI's own parameter types (real
    pointer depth, a recovered class name) are usually more accurate than
    Ghidra's erased ones. Returns "" (not a guess) if the definition can't
    be found.
    """
    for pattern in (rf'{re.escape(class_name)}::{re.escape(member_name)}\s*\(',
                    rf'(?<![\w:]){re.escape(member_name)}\s*\('):
        m = re.search(pattern, cpp)
        if m:
            open_idx = m.end() - 1
            close_idx = _matching_paren(cpp, open_idx)
            if close_idx is not None:
                return cpp[open_idx + 1:close_idx].strip()
    return ""


def _actual_is_const(cpp: str, class_name: str, member_name: str) -> bool:
    """
    Best-effort: does `cpp`'s own out-of-line definition mark this method
    `const`? Ghidra's own signature has no such concept at all -- it's a
    low-level ABI view with no notion of a const member function -- so
    this can only ever come from the AI's own definition. A synthesized
    declaration that doesn't carry it through is a declaration/definition
    mismatch: a real, observed compile error (`Piece::Draw() const`
    defined in recovered.cpp, plain `Draw()` declared in recovered.h).
    """
    for pattern in (rf'{re.escape(class_name)}::{re.escape(member_name)}\s*\(',
                    rf'(?<![\w:]){re.escape(member_name)}\s*\('):
        m = re.search(pattern, cpp)
        if m:
            open_idx = m.end() - 1
            close_idx = _matching_paren(cpp, open_idx)
            if close_idx is not None:
                brace_idx = cpp.find("{", close_idx)
                tail = cpp[close_idx + 1: brace_idx] if brace_idx != -1 else cpp[close_idx + 1:]
                return bool(re.search(r'\bconst\b', tail))
    return False


_FIELD_ACCESS_RE = re.compile(r'\bthis->(\w+)\b')


def _detect_fields(cpp: str) -> list:
    """
    Distinct `this->fieldName` accesses in one function's body, in
    first-seen order. This is the only source of field information
    available at all -- Ghidra's per-function signature has no concept of
    "fields", only parameters -- so unioning this across every member
    function of a class (see _synthesize_class_members) is how a
    synthesized class ends up with the fields its own methods actually
    need, not just the methods themselves.
    """
    seen = []
    for m in _FIELD_ACCESS_RE.finditer(cpp):
        if m.group(1) not in seen:
            seen.append(m.group(1))
    return seen


def _top_level_call_names(text: str) -> list:
    """
    Every identifier immediately followed by a `(` at paren-depth 0 within
    `text`, in order -- i.e. each top-level `name(...)` call, not one
    nested inside another's own arguments. Tracks depth explicitly rather
    than using a plain `\\w+\\s*\\(` scan, which doesn't respect nesting at
    all: a real, observed bug matched "Piece(" from *inside* a field
    initializer's own value (`m_piece(new Piece())`) as if it were its own
    separate top-level initializer-list entry, wrongly reporting "Piece"
    as a base class it had nothing to do with being a base of.
    """
    names = []
    depth = 0
    for i, c in enumerate(text):
        if c == "(":
            if depth == 0:
                j = i
                while j > 0 and (text[j - 1].isalnum() or text[j - 1] == "_"):
                    j -= 1
                name = text[j:i]
                if name:
                    names.append(name)
            depth += 1
        elif c == ")":
            depth -= 1
    return names


def _detect_base_class(cpp: str, class_name: str, known_class_names: set):
    """
    Best-effort: does this constructor's own body show a real base class?
    Two styles observed in practice --
      1. A genuine initializer list: `King::King() : Piece(this) { ... }`
         -- sits between the parameter list and the opening `{`.
      2. An explicit base-constructor call as the first statement in a
         C-style body: `Piece::Piece((Piece *)this);` -- sits after it.
    Searched separately, in their own region only: searching pattern 2
    over the *whole* text (declaration included) finds the constructor's
    own signature line first -- "King::King(" trivially matches "X::X("
    with X == class_name, which fails the `!= class_name` check and stops
    `re.search` from ever reaching the real base-constructor call in the
    body (a real, observed bug: `Piece::Piece((Piece *)this);` right there
    in the body went undetected because "King::King(" in the signature
    line above it matched first). Pattern 2 now scans *every* match in the
    body (not just the first) for the same reason pattern 1 scans every
    initializer-list entry below -- an unrelated early false match
    shouldn't stop the real one further down from ever being considered.

    Pattern 1 scans *every* top-level entry in the initializer list (see
    _top_level_call_names), not just the first, and only accepts one
    that's in `known_class_names` (every name this run has seen as *some*
    function's own `this`-typed class). Both a base-class call and a
    member-variable initializer look syntactically identical --
    `identifier(args)` either way -- so without that check, a real,
    observed bug matched `Piece() : m_ptr(nullptr), m_active(false) {}`'s
    own member initializer "m_ptr(nullptr)" as if "m_ptr" were Piece's
    base class ("m_ptr" is never any function's `this` type; "Piece" is).
    Returns None rather than guessing wrong if nothing in the list is a
    known class.
    """
    escaped = re.escape(class_name)
    brace_idx = cpp.find("{")
    header = cpp[:brace_idx] if brace_idx != -1 else cpp
    body = cpp[brace_idx:] if brace_idx != -1 else ""

    ctor_m = re.search(rf'\b{escaped}\s*(?:::\s*{escaped})?\s*\([^)]*\)\s*:\s*(.*)', header, re.DOTALL)
    if ctor_m:
        for name in _top_level_call_names(ctor_m.group(1)):
            if name != class_name and name in known_class_names:
                return name

    for m in re.finditer(r'\b(\w+)::\1\s*\(', body):
        if m.group(1) != class_name and m.group(1) in known_class_names:
            return m.group(1)
    return None


def _detect_init_list_fields(cpp: str, class_name: str, known_class_names: set) -> list:
    """
    Member names initialized via a constructor's own initializer list --
    `: field(value), other_field(value2) { ... }` -- as opposed to a
    `this->field = value;` assignment in the body, which is all
    _detect_fields() recognizes. The freer, idiomatic-conversion prompt
    now actively encourages this exact style, and a real, observed bug
    showed why that matters: `Piece::Piece() : m_data(nullptr),
    m_activeFlag(0) {}` initializes two members that _detect_fields()
    never sees, so the synthesized class ended up with a constructor
    initializing fields it never declared -- a guaranteed compile error.

    Every top-level initializer-list entry has the exact same shape as a
    base-class call (`identifier(args)`) -- see _detect_base_class, whose
    _top_level_call_names() is reused here for the same reason: a plain
    scan for any "identifier(" doesn't respect parenthesis nesting, so a
    field initialized with a nested constructor call as its own value
    (`m_piece(new Piece())`) would otherwise surface "Piece" -- from
    *inside* that value -- as if it were its own separate entry.

    Anything already recognized as a known class name is skipped (that's
    a base being constructed, not a field). As a second, defensive guard,
    anything starting with an uppercase letter is skipped too, even if
    it's not currently a known class -- real member variables in this
    codebase are consistently lower_snake/m_-prefixed, never PascalCase,
    so this catches the case where a genuine base class's own constructor
    just isn't part of this run (nothing in known_class_names to rule it
    out by name), without which it would otherwise get misfiled as a
    field (`int Piece;`) instead of silently doing nothing about it.
    """
    escaped = re.escape(class_name)
    brace_idx = cpp.find("{")
    header = cpp[:brace_idx] if brace_idx != -1 else cpp

    ctor_m = re.search(rf'\b{escaped}\s*(?:::\s*{escaped})?\s*\([^)]*\)\s*:\s*(.*)', header, re.DOTALL)
    if not ctor_m:
        return []

    fields = []
    for name in _top_level_call_names(ctor_m.group(1)):
        if (name != class_name and name not in known_class_names
                and not name[:1].isupper() and name not in fields):
            fields.append(name)
    return fields


def _qualify_member_definition(cpp: str, class_name: str, orig_name: str, member_name: str) -> str:
    """
    If `cpp`'s own out-of-line definition isn't already qualified as
    ClassName::member, insert the qualifier at the definition site. Leaves
    `cpp` untouched (rather than guessing) if the expected bare name can't
    be found at all.
    """
    if orig_name == class_name:
        bare_name, qualified = class_name, f"{class_name}::{class_name}"
    elif orig_name == "~" + class_name:
        bare_name, qualified = "~" + class_name, f"{class_name}::~{class_name}"
    else:
        bare_name, qualified = member_name, f"{class_name}::{member_name}"

    if qualified in cpp:
        return cpp

    m = re.search(rf'(?<![\w:]){re.escape(bare_name)}\s*\(', cpp)
    if not m:
        return cpp
    insert_at = m.start()
    return cpp[:insert_at] + class_name + "::" + cpp[insert_at:]


# Ghidra's own internal type spellings -- never valid C++ on their own, and
# they show up verbatim in raw signatures (both as parameter types and
# return types) wherever Ghidra couldn't resolve something to a real type.
# Longest-first so "undefined8" matches before the bare "undefined" prefix
# would otherwise win.
_GHIDRA_TYPE_SUBSTITUTIONS = {
    "undefined8": "uint64_t", "undefined4": "uint32_t",
    "undefined2": "uint16_t", "undefined1": "uint8_t",
    "undefined": "void", "longlong": "long long",
    "ulonglong": "unsigned long long", "uint": "unsigned int",
    "ushort": "unsigned short", "uchar": "unsigned char",
    "byte": "uint8_t", "sbyte": "int8_t", "code": "void",
}
_GHIDRA_TYPE_RE = re.compile(
    r'\b(' + '|'.join(sorted(map(re.escape, _GHIDRA_TYPE_SUBSTITUTIONS), key=len, reverse=True)) + r')\b'
)


def _sanitize_ghidra_types(text: str) -> str:
    return _GHIDRA_TYPE_RE.sub(lambda m: _GHIDRA_TYPE_SUBSTITUTIONS[m.group(1)], text)


def _is_operator_name(name: str) -> bool:
    return name.startswith("operator") and (
        len(name) == len("operator") or not name[len("operator")].isalnum()
    )


def _pointers_to_references(param_list: str) -> str:
    """
    Ghidra always spells a by-reference parameter as a pointer -- that's
    literally what a reference lowers to at the ABI level -- but a
    non-member `operator<<`/`operator>>` specifically requires a real
    class/enum *reference* argument to even be a valid overload at all;
    the C++ standard's operand rule doesn't accept a pointer for this,
    however related to a class it is.
    """
    return re.sub(r'(\w+)\s*\*', r'\1 &', param_list)


def _declaration(fn: "_FnRecord") -> str:
    """
    Build the forward declaration for a function.

    Primary path: use the Ghidra-provided signature (authoritative types and
    parameter count) but substitute the Ghidra placeholder name (FUN_xxx) with
    the semantic name the AI chose in the reconstructed code.

    Fallback: if Ghidra gave no signature, extract the declaration from the
    AI-generated cpp the old heuristic way.
    """
    if fn.signature:
        # Pull the function name out of the Ghidra signature, e.g.
        # "undefined8 FUN_140001330(undefined8 * param_1)"  →  "FUN_140001330".
        # The operator.new/operator.new[] alternative is tried first and
        # matched as one unit -- the plain identifier pattern alone stops at
        # the "." (not a word character), so it would only capture "new" out
        # of "operator.new" and then .replace() that bare "new" substring,
        # corrupting the result into "operator.operator.new" (a real,
        # observed bug) instead of leaving the correctly-spelled name alone.
        # The plain-identifier alternative also swallows a trailing bracketed
        # ABI tag Ghidra appends for some GCC symbols, e.g. "Draw[abi:cxx11]"
        # -- without it, that tag sits between the name and the "(", so the
        # whole match fails, and the code used to fall all the way through
        # to emitting Ghidra's raw signature completely unrenamed, tag and
        # all: "King * Draw[abi:cxx11](King * this);" is not valid C++ under
        # any circumstance (a real, observed bug). Matching (and therefore
        # replacing) the tag along with the name strips it from the result.
        m = re.search(r'\b(operator\.\w+(?:\[\])?|[A-Za-z_]\w*(?:\[[^\]]*\])?)\s*\(', fn.signature)
        if m:
            ghidra_name = m.group(1)
            decl = fn.signature.replace(ghidra_name, fn.name, 1)
        else:
            decl = fn.signature
        return decl.rstrip(";") + ";"

    return _extract_signature_fallback(fn.cpp)


def _extract_signature_fallback(cpp: str) -> str:
    """Heuristic fallback: fish the function signature out of AI-generated code."""
    SKIP = re.compile(r'^(struct|class|enum|typedef|extern)\b')
    in_block_comment = False
    lines = cpp.split("\n")

    for i, line in enumerate(lines):
        s = line.strip()
        if in_block_comment:
            if "*/" in s:
                in_block_comment = False
            continue
        if s.startswith("/*"):
            if "*/" not in s:
                in_block_comment = True
            continue
        if not s or s.startswith("//") or s.startswith("#"):
            continue
        if SKIP.match(s):
            continue
        if "(" not in s:
            continue
        if s.endswith(";") and "{" not in s:
            continue   # forward declaration, not a definition

        if "{" in s:
            return s.split("{")[0].rstrip() + ";"

        # Multi-line signature — confirm next non-blank line opens the body
        for j in range(i + 1, min(i + 5, len(lines))):
            next_s = lines[j].strip()
            if next_s.startswith("{"):
                return s + ";"
            if next_s and not next_s.startswith("//"):
                break

    return ""
